import json


s={'MP' : [{'census_dc': '465', 'census_sc': '23', 'district': 'Alirajpur', 'state': 'MP', 'district_deva': 'अलीराजपुर'},
{'census_dc': '461', 'census_sc': '23', 'district': 'Anuppur', 'state': 'MP', 'district_deva': 'अनुपपुर'},
{'census_dc': '459', 'census_sc': '23', 'district': 'Ashoknagar', 'state': 'MP', 'district_deva': 'अशोकनगर'},
{'census_dc': '457', 'census_sc': '23', 'district': 'Balaghat', 'state': 'MP', 'district_deva': 'बालाघाट'},
{'census_dc': '441', 'census_sc': '23', 'district': 'Barwani', 'state': 'MP', 'district_deva': 'बडवानी'},
{'census_dc': '447', 'census_sc': '23', 'district': 'Betul', 'state': 'MP', 'district_deva': 'बेतूल'},
{'census_dc': '420', 'census_sc': '23', 'district': 'Bhind', 'state': 'MP', 'district_deva': 'भिण्ड'},
{'census_dc': '444', 'census_sc': '23', 'district': 'Bhopal', 'state': 'MP', 'district_deva': 'भोपाल'},
{'census_dc': '467', 'census_sc': '23', 'district': 'Burhanpur', 'state': 'MP', 'district_deva': 'बुरहानपुर'},
{'census_dc': '425', 'census_sc': '23', 'district': 'Chhatarpur', 'state': 'MP', 'district_deva': 'छतरपुर'},
{'census_dc': '455', 'census_sc': '23', 'district': 'Chhindwara', 'state': 'MP', 'district_deva': 'छिन्दवाडा'},
{'census_dc': '428', 'census_sc': '23', 'district': 'Damoh', 'state': 'MP', 'district_deva': 'दमोह'},
{'census_dc': '422', 'census_sc': '23', 'district': 'Datia', 'state': 'MP', 'district_deva': 'दतिया'},
{'census_dc': '437', 'census_sc': '23', 'district': 'Dewas', 'state': 'MP', 'district_deva': 'देवास'},
{'census_dc': '438', 'census_sc': '23', 'district': 'Dhar', 'state': 'MP', 'district_deva': 'धार'},
{'census_dc': '453', 'census_sc': '23', 'district': 'Dindori', 'state': 'MP', 'district_deva': 'डिण्डोरी'},
{'census_dc': '458', 'census_sc': '23', 'district': 'Guna', 'state': 'MP', 'district_deva': 'गुना'},
{'census_dc': '421', 'census_sc': '23', 'district': 'Gwalior', 'state': 'MP', 'district_deva': 'ग्वालियर'},
{'census_dc': '448', 'census_sc': '23', 'district': 'Harda', 'state ': 'MP', 'district_deva': 'हरदा'},
{'census_dc': '449', 'census_sc': '23', 'district': 'Hoshangabad', 'state': 'MP', 'district_deva': 'होशंगाबाद'},
{'census_dc': '439', 'census_sc': '23', 'district': 'Indore', 'state': 'MP', 'district_deva': 'इन्दौर'},
{'census_dc': '451', 'census_sc': '23', 'district': 'Jabalpur', 'state': 'MP', 'district_deva': 'जबलपुर'},
{'census_dc': '464', 'census_sc': '23', 'district': 'Jhabua', 'state': 'MP', 'district_deva': 'झाबुआ'},
{'census_dc': '450', 'census_sc': '23', 'district': 'Katni', 'state': 'MP', 'district_deva': 'कटनी'},
{'census_dc': '466', 'census_sc': '23', 'district': 'Khandwa (East Nimar)', 'state': 'MP', 'district_deva': 'खण्डवा'},
{'census_dc': '440', 'census_sc': '23', 'district': 'Khargone (West Nimar)', 'state': 'MP', 'district_deva': 'खरगोन'},
{'census_dc': '454', 'census_sc': '23', 'district': 'Mandla', 'state': 'MP', 'district_deva': 'मण्डला'},
{'census_dc': '433', 'census_sc': '23', 'district': 'Mandsaur', 'state': 'MP', 'district_deva': 'मंदसौर'},
{'census_dc': '419', 'census_sc': '23', 'district': 'Morena', 'state': 'MP', 'district_deva': 'मुरैना'},
{'census_dc': '452', 'census_sc': '23', 'district': 'Narsimhapur', 'state': 'MP', 'district_deva': 'नरसिंहपुर'},
{'census_dc': '432', 'census_sc': '23', 'district': 'Neemuch', 'state': 'MP', 'district_deva': 'नीमच'},
{'census_dc': '426', 'census_sc': '23', 'district': 'Panna', 'state': 'MP', 'district_deva': 'पन्ना'},
{'census_dc': '446', 'census_sc': '23', 'district': 'Raisen', 'state': 'MP', 'district_deva': 'रायसेन'},
{'census_dc': '442', 'census_sc': '23', 'district': 'Rajgarh', 'state': 'MP', 'district_deva': 'राजगढ'},
{'census_dc': '434', 'census_sc': '23', 'district': 'Ratlam', 'state': 'MP', 'district_deva': 'रतलाम'},
{'census_dc': '430', 'census_sc': '23', 'district': 'Rewa', 'state': 'MP', 'district_deva': 'रीवा'},
{'census_dc': '427', 'census_sc': '23', 'district': 'Sagar', 'state': 'MP', 'district_deva': 'सागर'},
{'census_dc': '429', 'census_sc': '23', 'district': 'Satna', 'state': 'MP', 'district_deva': 'सतना'},
{'census_dc': '445', 'census_sc': '23', 'district': 'Sehore', 'state': 'MP', 'district_deva': 'सीहोर'},
{'census_dc': '456', 'census_sc': '23', 'district': 'Seoni', 'state': 'MP', 'district_deva': 'सिवनी'},
{'census_dc': '460', 'census_sc': '23', 'district': 'Shahdol', 'state': 'MP', 'district_deva': 'शहडोल'},
{'census_dc': '436', 'census_sc': '23', 'district': 'Shajapur', 'state': 'MP', 'district_deva': 'शाजापुर'},
{'census_dc': '418', 'census_sc': '23', 'district': 'Sheopur', 'state': 'MP', 'district_deva': 'श्योपुर'},
{'census_dc': '423', 'census_sc': '23', 'district': 'Shivpuri', 'state': 'MP', 'district_deva': 'शिवपुरी'},
{'census_dc': '462', 'census_sc': '23', 'district': 'Sidhi', 'state': 'MP', 'district_deva': 'सीधी'},
{'census_dc': '463', 'census_sc': '23', 'district': 'Singrauli', 'state': 'MP', 'district_deva': 'सिंगरौली'},
{'census_dc': '424', 'census_sc': '23', 'district': 'Tikamgarh', 'state': 'MP', 'district_deva': 'टीकमगढ'},
{'census_dc': '435', 'census_sc': '23', 'district': 'Ujjain', 'state': 'MP', 'district_deva': 'उज्जैन'},
{'census_dc': '431', 'census_sc': '23', 'district': 'Umaria', 'state': 'MP', 'district_deva': 'उमरिया'},
{'census_dc': '443', 'census_sc': '23', 'district': 'Vidisha', 'state': 'MP', 'district_deva': 'विदिशा'},
{'census_dc': '000', 'census_sc': '00', 'district': 'Agar Malwa', 'state': 'MP', 'district_deva': 'आगर मालवा'}]}


with open("MP_updated.json", "w") as file: 
    json.dump(s, file)